[Build] Jenkins: Show better error message when SCENARIOS_RUNNER_DOCKER_TAG is missing or empty
* https://auto-jenkins.lgsvl.net/job/simulator-release-cloud/30 failed with:

  [Pipeline] { (bundleScenariosRunner)
  [Pipeline] dir
  03:57:22  Running in /home/jenkins/workspace/simulator-cloud-release-2019.3.15f1/Jenkins
  [Pipeline] {
  [Pipeline] sh
  03:57:23  + docker pull auto-gitlab.lgsvl.net:4567/
  03:57:23  invalid reference format
  03:57:23  + echo ABORT: cannot pull auto-gitlab.lgsvl.net:4567/
  03:57:23  ABORT: cannot pull auto-gitlab.lgsvl.net:4567/
  03:57:23  + exit 1

* because newly added parameter isn't added in jenkins job until the updated pipeline
  is executed at least once and unfortunately, when it's not picked there yet,
  it won't even use the default value specified in the pipeline and will just
  run with empty value which might cause unexpected build failures like this

* use ${env.OUTPUT_SUFFIX} instead of ${OUTPUT_SUFFIX}, because when "error"
  triggers "post" early it fails with:
  groovy.lang.MissingPropertyException: No such property: OUTPUT_SUFFIX for class: groovy.lang.Binding
  as in:
  https://auto-jenkins.lgsvl.net/view/Jenkins%20test/job/simulator-jansa-jenkins-wip-test/123/console

* testing params.SCENARIOS_RUNNER_DOCKER_TAG for null isn't enough,
  because it isn't null as long as the parameter definition appears
  in parameters section

* testing all params for empty doesn't help much as well, because some like
  BUILD_SIMULATOR_* in Bundle jobs could be intentinally set to empty

* unfortunatelly jenkins pipeline documentation still lacks:
  https://issues.jenkins.io/browse/INFRA-1053