Assets: add assert for null assetGuid and show its type
* will show at least the type of asset which was null instead of
  completely useless error shown in exception:

  PLC_B_15 - Traceback (most recent call last):
    File "/OE/projects/lgsvl/HDRP/PythonApi/examples/NHTSA/Perform-Lane-Change/PLC_B_15.py", line 44, in <module>
      ego = sim.add_agent(env.str("LGSVL__VEHICLE_0", lgsvl.wise.DefaultAssets.ego_lincoln2017mkz_apollo5_modular), lgsvl.AgentType.EGO, egoState)
    File "/OE/projects/lgsvl/HDRP/PythonApi/lgsvl/utils.py", line 23, in new_f
      return f(*args, **kwargs)
    File "/OE/projects/lgsvl/HDRP/PythonApi/lgsvl/simulator.py", line 162, in add_agent
      uid = self.remote.command("simulator/add_agent", args)
    File "/OE/projects/lgsvl/HDRP/PythonApi/lgsvl/remote.py", line 69, in command
      raise Exception(data["error"])
  Exception: Value cannot be null.
  Parameter name: path2

* the Player.log exception with a stack trace shows at least some context for this
  error, but still doesn't show which type of asset it was (so it's still difficult
  to guess which assetGuid was null (Bridge in this case):

  Failed to start 'Random' simulation

  ArgumentNullException: Value cannot be null.
  Parameter name: path2
    at System.IO.Path.Combine (System.String path1, System.String path2) [0x00011] in <eae584ce26bc40229c1b1aa476bfa589>:0
    at Simulator.Web.WebUtilities.GenerateLocalPath (System.String assetGuid, Simulator.BundleConfig+BundleTypes type) [0x00020] in <de43adacb40d4d31837e9d3d6facd55d>:0
    at Simulator.Web.DownloadManager.GetAsset (Simulator.BundleConfig+BundleTypes type, System.String assetGuid, System.String name, System.IProgress`1[T] progressCallback) [0x0009b] in <de43adacb40d4d31837e9d3d6facd55d>:0
    at Simulator.Loader+<StartSimulation>d__43.MoveNext () [0x002da] in <de43adacb40d4d31837e9d3d6facd55d>:0
  UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
  UnityEngine.DebugLogHandler:LogException(Exception, Object)
  UnityEngine.Logger:LogException(Exception, Object)
  UnityEngine.Debug:LogException(Exception)
  Simulator.<StartSimulation>d__43:MoveNext()
  System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<StartSimulation>d__43&)
  Simulator.Loader:StartSimulation(SimulationData)
  <>c__DisplayClass18_1:<Parse>b__2()
  ConnectionManager:Update()

  loader status: Loading->Error Value cannot be null.
  Parameter name: path2

* with this change applied it's at least showing the type of asset which is null:

  PLC_B_15 - Traceback (most recent call last):
    File "/OE/projects/lgsvl/HDRP/PythonApi/examples/NHTSA/Perform-Lane-Change/PLC_B_15.py", line 44, in <module>
      ego = sim.add_agent(env.str("LGSVL__VEHICLE_0", lgsvl.wise.DefaultAssets.ego_lincoln2017mkz_apollo5_modular), lgsvl.AgentType.EGO, egoState)
    File "/OE/projects/lgsvl/HDRP/PythonApi/lgsvl/utils.py", line 23, in new_f
      return f(*args, **kwargs)
    File "/OE/projects/lgsvl/HDRP/PythonApi/lgsvl/simulator.py", line 162, in add_agent
      uid = self.remote.command("simulator/add_agent", args)
    File "/OE/projects/lgsvl/HDRP/PythonApi/lgsvl/remote.py", line 69, in command
      raise Exception(data["error"])
  Exception: assetGuid must not be null when trying to get $Bridge asset.
  Assertion failure. Value was Null
  Expected: Value was not Null