ScenarioManager: don't try to set non-existent IsInitializing property
* it exists only in vse branch where it was added with this commit:
  https://auto-gitlab.lgsvl.net/HDRP/Simulator/commit/08038b7a2b87e1608aebe757e74d6acd774006fb#b8a2054485aa4aa693a454077a9753bb5fed45cc
  but it doesn't exist in master causing:
  04:10:58  Assets/Scripts/ScenarioEditor/Managers/ScenarioManager.cs(310,13): error CS0103: The name 'IsInitializing' does not exist in the current context

* and assign to private isInitialized property directly to fix:
  04:10:58  Assets/Scripts/ScenarioEditor/Managers/ScenarioManager.cs(311,13): error CS0200: Property or indexer 'ScenarioManager.IsInitialized' cannot be assigned to -- it is read only