Jenkins: Fix unityci based docker image
* switches from ubuntu-18.04 to ubuntu-20.04 to fix vulkan renderer

* install libvulkan1 and remove ca-certificates
* update the comments

* we're using -force-vulkan in our builds

* install libvulkan1 as it was before the switch to unityci docker image
  because without this Unity will fail to detect Vulkan and use llvmpipe
  renderer instead, which results in all black preview images in Assets
  bundles and we also use -force-vulkan, so it's a bit surprising that
  missing libvulkan1 wasn't fatal error

* without mesa-vulkan-drivers vulkaninfo would fail with:
  root@0ea8660cc34a:/# vulkaninfo
  ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: Could not get 'vkCreateInstance' via 'vk_icdGetInstanceProcAddr' for ICD libGLX_nvidia.so.0
  Cannot create Vulkan instance.
  This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
  /build/vulkan-tools-KEbD_A/vulkan-tools-1.2.131.1+dfsg1/vulkaninfo/vulkaninfo.h:371: failed with ERROR_INCOMPATIBLE_DRIVER

  but having mesa-vulkan-drivers in the image breaks Unity trying to use Vulkan

* I don't see ca-certificates being used

* use latest hdrp/unityci/editor docker image built in:
  https://auto-jenkins.lgsvl.net/view/docker/job/unityci-docker-image/28/

* don't use xvfb-run

* update image-info-lgsvl.source
  when starting from editor-lgsvl instead of regular editor from Docker Hub
  the /opt/unity/image-info-lgsvl.source would already be there
  but we don't overwrite it, instead add another section after
  IMAGE_APP="unity-editor-simulator"
  showing few more details, but drop UNITY_CHANGESET, UNITY_MODULES
  params as they are never set when building ${UNITY_DOCKER_IMAGE_TAG}-simulator
  image and we "inherit" them from editor-lgsvl image used in EDITOR_DOCKER_IMAGE